/*
 * initialisation_code.c
 *
 *  Created on: Aug 22, 2023
 *      Author: ashlo
 */
#include <custom_h.h>

curr_obj initialisation_code(curr_obj currObj)
{

	XGpio GPIO_PCB_32INPUTS_Inst;
	XGpio_Initialize(&GPIO_PCB_32INPUTS_Inst, GPIO_PCB_32INPUTS_ID);
	XGpio GPIO_PCB_32OUTPUTS_Inst;
	XGpio_Initialize(&GPIO_PCB_32OUTPUTS_Inst, GPIO_PCB_32OUTPUTS_ID);
	XGpio GPIO_PCB_32INPUTS_1_Inst;
	XGpio_Initialize(&GPIO_PCB_32INPUTS_1_Inst, GPIO_PCB_32INPUTS_1_ID);
	XGpio GPIO_PCB_32OUTPUTS_1_Inst;
	XGpio_Initialize(&GPIO_PCB_32OUTPUTS_1_Inst, GPIO_PCB_32OUTPUTS_1_ID);
	XGpio GPIO_PCB_32INPUTS_2_Inst;
	XGpio_Initialize(&GPIO_PCB_32INPUTS_2_Inst, GPIO_PCB_32INPUTS_2_ID);
	XGpio GPIO_PCB_32OUTPUTS_2_Inst;
	XGpio_Initialize(&GPIO_PCB_32OUTPUTS_2_Inst, GPIO_PCB_32OUTPUTS_2_ID);
	XGpio GPIO_PCB_32OUTPUTS_100_Inst;
	XGpio_Initialize(&GPIO_PCB_32OUTPUTS_100_Inst, GPIO_PCB_32OUTPUTS_100_ID);
	XGpio GPIO_PCB_HS_Inst;
	XGpio_Initialize(&GPIO_PCB_HS_Inst, GPIO_PCB_HS_ID);
	XGpio GPIO_PCB_HS_Relaxed_Inst;
	XGpio_Initialize(&GPIO_PCB_HS_Relaxed_Inst, GPIO_PCB_HS_Relaxed_ID);




	//GPIO_MODE_READ_WRITE
	XGpio GPIO_MODE_READ_WRITE_Inst;
	XGpio_Initialize(&GPIO_MODE_READ_WRITE_Inst, GPIO_MODE_READ_WRITE_ID);
	u8 GPIO_MODE_READ_WRITE_DATA=0;//0=C-INPUT 1=MODE_WRITE; 2=MODE_READ; >2 = RESTRICTED-DO NOT USE// MODE_C set as default
	XGpio_DiscreteWrite(&GPIO_MODE_READ_WRITE_Inst,1,GPIO_MODE_READ_WRITE_DATA);

	//READ TIMING RELATED GPIOS
	XGpio READ_TIMING_1_MODE_R_WB_START_READ_GPIO_Inst;
	XGpio_Initialize(&READ_TIMING_1_MODE_R_WB_START_READ_GPIO_Inst, READ_TIMING_1_MODE_R_WB_START_READ_GPIO_ID);
	u8 READ_TIMING_1_MODE_R_WB_START_READ_GPIO_DATA=0;
	XGpio_DiscreteWrite(&READ_TIMING_1_MODE_R_WB_START_READ_GPIO_Inst,1,READ_TIMING_1_MODE_R_WB_START_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_2_MODE_R_WB_STOP_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_2_MODE_R_WB_STOP_READ_GPIO_Inst, GPIO_READ_TIMING_2_MODE_R_WB_STOP_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_2_MODE_R_WB_STOP_READ_GPIO_DATA=0;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_2_MODE_R_WB_STOP_READ_GPIO_Inst,1,GPIO_READ_TIMING_2_MODE_R_WB_STOP_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_3_PRE_DR_EN_START_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_3_PRE_DR_EN_START_READ_GPIO_Inst, GPIO_READ_TIMING_3_PRE_DR_EN_START_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_3_PRE_DR_EN_START_READ_GPIO_DATA=6;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_3_PRE_DR_EN_START_READ_GPIO_Inst,1,GPIO_READ_TIMING_3_PRE_DR_EN_START_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_4_PRE_DR_EN_STOP_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_4_PRE_DR_EN_STOP_READ_GPIO_Inst, GPIO_READ_TIMING_4_PRE_DR_EN_STOP_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_4_PRE_DR_EN_STOP_READ_GPIO_DATA=10;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_4_PRE_DR_EN_STOP_READ_GPIO_Inst,1,GPIO_READ_TIMING_4_PRE_DR_EN_STOP_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_5_WWL_EN_START_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_5_WWL_EN_START_READ_GPIO_Inst, GPIO_READ_TIMING_5_WWL_EN_START_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_5_WWL_EN_START_READ_GPIO_DATA=6;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_5_WWL_EN_START_READ_GPIO_Inst,1,GPIO_READ_TIMING_5_WWL_EN_START_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_6_WWL_EN_STOP_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_6_WWL_EN_STOP_READ_GPIO_Inst, GPIO_READ_TIMING_6_WWL_EN_STOP_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_6_WWL_EN_STOP_READ_GPIO_DATA=8;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_6_WWL_EN_STOP_READ_GPIO_Inst,1,GPIO_READ_TIMING_6_WWL_EN_STOP_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_7_RW_SA_EN_START_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_7_RW_SA_EN_START_READ_GPIO_Inst, GPIO_READ_TIMING_7_RW_SA_EN_START_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_7_RW_SA_EN_START_READ_GPIO_DATA=7;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_7_RW_SA_EN_START_READ_GPIO_Inst,1,GPIO_READ_TIMING_7_RW_SA_EN_START_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_8_RW_SA_EN_STOP_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_8_RW_SA_EN_STOP_READ_GPIO_Inst, GPIO_READ_TIMING_8_RW_SA_EN_STOP_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_8_RW_SA_EN_STOP_READ_GPIO_DATA=10;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_8_RW_SA_EN_STOP_READ_GPIO_Inst,1,GPIO_READ_TIMING_8_RW_SA_EN_STOP_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_9_CLK_B_START_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_9_CLK_B_START_READ_GPIO_Inst, GPIO_READ_TIMING_9_CLK_B_START_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_9_CLK_B_START_READ_GPIO_DATA=10;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_9_CLK_B_START_READ_GPIO_Inst,1,GPIO_READ_TIMING_9_CLK_B_START_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_10_CLK_B_STOP_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_10_CLK_B_STOP_READ_GPIO_Inst, GPIO_READ_TIMING_10_CLK_B_STOP_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_10_CLK_B_STOP_READ_GPIO_DATA=11;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_10_CLK_B_STOP_READ_GPIO_Inst,1,GPIO_READ_TIMING_10_CLK_B_STOP_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_11_CLK_C_START_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_11_CLK_C_START_READ_GPIO_Inst, GPIO_READ_TIMING_11_CLK_C_START_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_11_CLK_C_START_READ_GPIO_DATA=8;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_11_CLK_C_START_READ_GPIO_Inst,1,GPIO_READ_TIMING_11_CLK_C_START_READ_GPIO_DATA);

	XGpio GPIO_READ_TIMING_12_CLK_C_STOP_READ_GPIO_Inst;
	XGpio_Initialize(&GPIO_READ_TIMING_12_CLK_C_STOP_READ_GPIO_Inst, GPIO_READ_TIMING_12_CLK_C_STOP_READ_GPIO_ID);
	u8 GPIO_READ_TIMING_12_CLK_C_STOP_READ_GPIO_DATA=9;
	XGpio_DiscreteWrite(&GPIO_READ_TIMING_12_CLK_C_STOP_READ_GPIO_Inst,1,GPIO_READ_TIMING_12_CLK_C_STOP_READ_GPIO_DATA);

	//WRITE TIMING RELATED GPIOS

	XGpio GPIO_WRITE_TIMING_1_MODE_R_WB_START_WRITE_GPIO_Inst;
	XGpio_Initialize(&GPIO_WRITE_TIMING_1_MODE_R_WB_START_WRITE_GPIO_Inst, GPIO_WRITE_TIMING_1_MODE_R_WB_START_WRITE_GPIO_ID);
	u8 GPIO_WRITE_TIMING_1_MODE_R_WB_START_WRITE_GPIO_DATA=6;
	XGpio_DiscreteWrite(&GPIO_WRITE_TIMING_1_MODE_R_WB_START_WRITE_GPIO_Inst,1,GPIO_WRITE_TIMING_1_MODE_R_WB_START_WRITE_GPIO_DATA);

	XGpio GPIO_WRITE_TIMING_2_MODE_R_WB_STOP_WRITE_GPIO_Inst;
	XGpio_Initialize(&GPIO_WRITE_TIMING_2_MODE_R_WB_STOP_WRITE_GPIO_Inst, GPIO_WRITE_TIMING_2_MODE_R_WB_STOP_WRITE_GPIO_ID);
	u8 GPIO_WRITE_TIMING_2_MODE_R_WB_STOP_WRITE_GPIO_DATA=7;
	XGpio_DiscreteWrite(&GPIO_WRITE_TIMING_2_MODE_R_WB_STOP_WRITE_GPIO_Inst,1,GPIO_WRITE_TIMING_2_MODE_R_WB_STOP_WRITE_GPIO_DATA);

	XGpio GPIO_WRITE_TIMING_3_PRE_DR_EN_START_WRITE_GPIO_Inst;
	XGpio_Initialize(&GPIO_WRITE_TIMING_3_PRE_DR_EN_START_WRITE_GPIO_Inst, GPIO_WRITE_TIMING_3_PRE_DR_EN_START_WRITE_GPIO_ID);
	u8 GPIO_WRITE_TIMING_3_PRE_DR_EN_START_WRITE_GPIO_DATA=6;
	XGpio_DiscreteWrite(&GPIO_WRITE_TIMING_3_PRE_DR_EN_START_WRITE_GPIO_Inst,1,GPIO_WRITE_TIMING_3_PRE_DR_EN_START_WRITE_GPIO_DATA);

	XGpio GPIO_WRITE_TIMING_4_PRE_DR_EN_STOP_WRITE_GPIO_Inst;
	XGpio_Initialize(&GPIO_WRITE_TIMING_4_PRE_DR_EN_STOP_WRITE_GPIO_Inst, GPIO_WRITE_TIMING_4_PRE_DR_EN_STOP_WRITE_GPIO_ID);
	u8 GPIO_WRITE_TIMING_4_PRE_DR_EN_STOP_WRITE_GPIO_DATA=7;
	XGpio_DiscreteWrite(&GPIO_WRITE_TIMING_4_PRE_DR_EN_STOP_WRITE_GPIO_Inst,1,GPIO_WRITE_TIMING_4_PRE_DR_EN_STOP_WRITE_GPIO_DATA);

	XGpio GPIO_WRITE_TIMING_5_WWL_EN_START_WRITE_GPIO_Inst;
	XGpio_Initialize(&GPIO_WRITE_TIMING_5_WWL_EN_START_WRITE_GPIO_Inst, GPIO_WRITE_TIMING_5_WWL_EN_START_WRITE_GPIO_ID);
	u8 GPIO_WRITE_TIMING_5_WWL_EN_START_WRITE_GPIO_DATA=6;
	XGpio_DiscreteWrite(&GPIO_WRITE_TIMING_5_WWL_EN_START_WRITE_GPIO_Inst,1,GPIO_WRITE_TIMING_5_WWL_EN_START_WRITE_GPIO_DATA);

	XGpio GPIO_WRITE_TIMING_6_WWL_EN_STOP_WRITE_GPIO_Inst;
	XGpio_Initialize(&GPIO_WRITE_TIMING_6_WWL_EN_STOP_WRITE_GPIO_Inst, GPIO_WRITE_TIMING_6_WWL_EN_STOP_WRITE_GPIO_ID);
	u8 GPIO_WRITE_TIMING_6_WWL_EN_STOP_WRITE_GPIO_DATA=7;
	XGpio_DiscreteWrite(&GPIO_WRITE_TIMING_6_WWL_EN_STOP_WRITE_GPIO_Inst,1,GPIO_WRITE_TIMING_6_WWL_EN_STOP_WRITE_GPIO_DATA);


	//HYBRID MODE RELATED TIMING GPIOS


	XGpio GPIO_MODE_IMC_Inst;
	XGpio_Initialize(&GPIO_MODE_IMC_Inst, GPIO_MODE_IMC_ID);
	u8 GPIO_MODE_IMC_DATA=0;
	XGpio_DiscreteWrite(&GPIO_MODE_IMC_Inst,1,GPIO_MODE_IMC_DATA);

	XGpio GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_DATA=7;//7 is exact//first try =40
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA=31;//15 is exact//first try =120//second try=31
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_3_CLK_DFF_EXT_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_3_CLK_DFF_EXT_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_3_CLK_DFF_EXT_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_3_CLK_DFF_EXT_START_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA-1;//14 is exact
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_3_CLK_DFF_EXT_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_3_CLK_DFF_EXT_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_4_CLK_DFF_EXT_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_4_CLK_DFF_EXT_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_4_CLK_DFF_EXT_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_4_CLK_DFF_EXT_STOP_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA;//15 is exact
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_4_CLK_DFF_EXT_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_4_CLK_DFF_EXT_STOP_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_5_DATACM_EN_EXT_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_5_DATACM_EN_EXT_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_5_DATACM_EN_EXT_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_5_DATACM_EN_EXT_START_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_DATA;//2 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_5_DATACM_EN_EXT_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_5_DATACM_EN_EXT_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_6_DATACM_EN_EXT_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_6_DATACM_EN_EXT_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_6_DATACM_EN_EXT_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_6_DATACM_EN_EXT_STOP_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA;//15 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_6_DATACM_EN_EXT_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_6_DATACM_EN_EXT_STOP_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_7_DATASUB_EN_EXT_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_7_DATASUB_EN_EXT_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_7_DATASUB_EN_EXT_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_7_DATASUB_EN_EXT_START_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_DATA;//2 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_7_DATASUB_EN_EXT_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_7_DATASUB_EN_EXT_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_8_DATASUB_EN_EXT_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_8_DATASUB_EN_EXT_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_8_DATASUB_EN_EXT_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_8_DATASUB_EN_EXT_STOP_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA;//15 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_8_DATASUB_EN_EXT_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_8_DATASUB_EN_EXT_STOP_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_9_RESET_GLOBALTIMER_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_9_RESET_GLOBALTIMER_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_9_RESET_GLOBALTIMER_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_9_RESET_GLOBALTIMER_START_HYBRID_GPIO_DATA=1;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_9_RESET_GLOBALTIMER_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_9_RESET_GLOBALTIMER_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_10_RESET_GLOBALTIMER_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_10_RESET_GLOBALTIMER_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_10_RESET_GLOBALTIMER_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_10_RESET_GLOBALTIMER_STOP_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA;//15 is exact
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_10_RESET_GLOBALTIMER_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_10_RESET_GLOBALTIMER_STOP_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_11_RWL_EN_EXT_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_11_RWL_EN_EXT_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_11_RWL_EN_EXT_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_11_RWL_EN_EXT_START_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_DATA;//1 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_11_RWL_EN_EXT_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_11_RWL_EN_EXT_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_12_RWL_EN_EXT_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_12_RWL_EN_EXT_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_12_RWL_EN_EXT_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_12_RWL_EN_EXT_STOP_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA;//15 is exact
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_12_RWL_EN_EXT_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_12_RWL_EN_EXT_STOP_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_13_REFCM_EN_EXT_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_13_REFCM_EN_EXT_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_13_REFCM_EN_EXT_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_13_REFCM_EN_EXT_START_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_DATA;//2 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_13_REFCM_EN_EXT_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_13_REFCM_EN_EXT_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_14_REFCM_EN_EXT_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_14_REFCM_EN_EXT_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_14_REFCM_EN_EXT_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_14_REFCM_EN_EXT_STOP_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA;//15 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_14_REFCM_EN_EXT_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_14_REFCM_EN_EXT_STOP_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_15_REFSUB_EN_EXT_START_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_15_REFSUB_EN_EXT_START_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_15_REFSUB_EN_EXT_START_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_15_REFSUB_EN_EXT_START_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_1_ADCSTART_EXT_START_HYBRID_GPIO_DATA;//2 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_15_REFSUB_EN_EXT_START_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_15_REFSUB_EN_EXT_START_HYBRID_GPIO_DATA);

	XGpio GPIO_HYBRID_TIMING_16_REFSUB_EN_EXT_STOP_HYBRID_GPIO_Inst;
	XGpio_Initialize(&GPIO_HYBRID_TIMING_16_REFSUB_EN_EXT_STOP_HYBRID_GPIO_Inst, GPIO_HYBRID_TIMING_16_REFSUB_EN_EXT_STOP_HYBRID_GPIO_ID);
	u8 GPIO_HYBRID_TIMING_16_REFSUB_EN_EXT_STOP_HYBRID_GPIO_DATA=GPIO_HYBRID_TIMING_2_ADCSTART_EXT_STOP_HYBRID_GPIO_DATA;//15 is exact;
	XGpio_DiscreteWrite(&GPIO_HYBRID_TIMING_16_REFSUB_EN_EXT_STOP_HYBRID_GPIO_Inst,1,GPIO_HYBRID_TIMING_16_REFSUB_EN_EXT_STOP_HYBRID_GPIO_DATA);

	//INTERNAL MODE RELATED TIMING GPIOS
	XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
	XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
	// TOPSW RUN WAS WITH 60 30/10/2023 08:30 PM
//	u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=60;//Actually a 10 bit number in Block Diagram=> Accuracy was with 170 (26/10/2023 12:41AM)
	// ACCURACY RUN
	//u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=170;
//	// Internal-1X ADC in 2-bit mode- 258ns required as per simulation
//	u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=26;//260ns
//	// Internal-1X ADC in 3-bit mode- 	305ns required as per simulation
//	u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=31;//310ns
//// Internal-1X ADC in 4-bit mode- 351ns required as per simulation TOPSW RUN WAS on 02/02/2024 04:28 PM
//		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=36;//353ns
// Internal-1X ADC in 5-bit mode- 400ns required as per simulation TOPSW RUN WAS on 02/02/2024 04:28 PM
			u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=40;//400ns
	XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);


	//GPIO_COUNTSTOP_Relaxed
	XGpio GPIO_COUNTSTOP_Relaxed_Inst;
	XGpio_Initialize(&GPIO_COUNTSTOP_Relaxed_Inst, GPIO_COUNTSTOP_Relaxed_ID);
	u16 GPIO_COUNTSTOP_Relaxed_DATA=GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA*4+20;//4IMGs and a buffer counting time of 20
	XGpio_DiscreteWrite(&GPIO_COUNTSTOP_Relaxed_Inst,1,GPIO_COUNTSTOP_Relaxed_DATA);


// ASHWIN ADDED STARTS HERE
// FASTSCAN GPIOs
XGpio GPIO_FASTSCAN_RESET_FASTSCAN_Inst;
XGpio_Initialize(&GPIO_FASTSCAN_RESET_FASTSCAN_Inst, GPIO_FASTSCAN_RESET_FASTSCAN_DEVICE_ID);
XGpio GPIO_FASTSCAN_GPIO_CONTROL_SETTINGS_Inst;
XGpio_Initialize(&GPIO_FASTSCAN_GPIO_CONTROL_SETTINGS_Inst, GPIO_FASTSCAN_GPIO_CONTROL_SETTINGS_DEVICE_ID);
XGpio GPIO_FASTSCAN_GPIO_WIDTH_SETTINGS_Inst;
XGpio_Initialize(&GPIO_FASTSCAN_GPIO_WIDTH_SETTINGS_Inst, GPIO_FASTSCAN_GPIO_WIDTH_SETTINGS_DEVICE_ID);

XGpio GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK67_Inst;
XGpio_Initialize(&GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK67_Inst, GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK67_DEVICE_ID);
XGpio GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK45_Inst;
XGpio_Initialize(&GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK45_Inst, GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK45_DEVICE_ID);
XGpio GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK23_Inst;
XGpio_Initialize(&GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK23_Inst, GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK23_DEVICE_ID);
XGpio GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK01_Inst;
XGpio_Initialize(&GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK01_Inst, GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK01_DEVICE_ID);

XGpio GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK67_Inst;
XGpio_Initialize(&GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK67_Inst, GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK67_DEVICE_ID);
XGpio GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK45_Inst;
XGpio_Initialize(&GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK45_Inst, GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK45_DEVICE_ID);
XGpio GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK23_Inst;
XGpio_Initialize(&GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK23_Inst, GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK23_DEVICE_ID);
XGpio GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK01_Inst;
XGpio_Initialize(&GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK01_Inst, GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK01_DEVICE_ID);

XGpio GPIO_FASTSCAN_SCAN_DONE_Inst;
XGpio_Initialize(&GPIO_FASTSCAN_SCAN_DONE_Inst, GPIO_FASTSCAN_SCAN_DONE_DEVICE_ID);

// TOPSW GPIOs
XGpio GPIO_TOPSW_Inst;
XGpio_Initialize(&GPIO_TOPSW_Inst, GPIO_TOPSW_DEVICE_ID);
// ASHWIN ADDED ENDS HERE


currObj.GPIO_PCB_32INPUTS_Inst=GPIO_PCB_32INPUTS_Inst;
currObj.GPIO_PCB_32OUTPUTS_Inst=GPIO_PCB_32OUTPUTS_Inst;
currObj.GPIO_PCB_32INPUTS_1_Inst=GPIO_PCB_32INPUTS_1_Inst;
currObj.GPIO_PCB_32OUTPUTS_1_Inst=GPIO_PCB_32OUTPUTS_1_Inst;
currObj.GPIO_PCB_32INPUTS_2_Inst=GPIO_PCB_32INPUTS_2_Inst;
currObj.GPIO_PCB_32OUTPUTS_2_Inst=GPIO_PCB_32OUTPUTS_2_Inst;
currObj.GPIO_PCB_32OUTPUTS_100_Inst=GPIO_PCB_32OUTPUTS_100_Inst;
currObj.GPIO_MODE_READ_WRITE_Inst=GPIO_MODE_READ_WRITE_Inst;
currObj.GPIO_MODE_IMC_Inst=GPIO_MODE_IMC_Inst;
currObj.GPIO_PCB_HS_Inst=GPIO_PCB_HS_Inst;
currObj.GPIO_PCB_HS_Relaxed_Inst=GPIO_PCB_HS_Relaxed_Inst;

// ASHWIN ADDED STARTS HERE
// FASTSCAN GPIOs
currObj.GPIO_FASTSCAN_RESET_FASTSCAN_Inst=GPIO_FASTSCAN_RESET_FASTSCAN_Inst;
currObj.GPIO_FASTSCAN_GPIO_CONTROL_SETTINGS_Inst=GPIO_FASTSCAN_GPIO_CONTROL_SETTINGS_Inst;
currObj.GPIO_FASTSCAN_GPIO_WIDTH_SETTINGS_Inst=GPIO_FASTSCAN_GPIO_WIDTH_SETTINGS_Inst;

currObj.GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK_Inst[3]=GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK67_Inst;
currObj.GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK_Inst[2]=GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK45_Inst;
currObj.GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK_Inst[1]=GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK23_Inst;
currObj.GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK_Inst[0]=GPIO_FASTSCANIN_GPIO_PARALLEL_IN_BANK01_Inst;

currObj.GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK_Inst[3]=GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK67_Inst;
currObj.GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK_Inst[2]=GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK45_Inst;
currObj.GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK_Inst[1]=GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK23_Inst;
currObj.GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK_Inst[0]=GPIO_FASTSCANOUT_GPIO_PARALLEL_OUT_BANK01_Inst;

currObj.GPIO_FASTSCAN_SCAN_DONE_Inst=GPIO_FASTSCAN_SCAN_DONE_Inst;
// TOPSW GPIOs
currObj.GPIO_TOPSW_Inst=GPIO_TOPSW_Inst;
// ASHWIN ADDED ENDS HERE

// GPIO_HYBRIDPIPELINETOPSW_VARS
XGpio GPIO_HYBRIDPIPELINETOPSW_VARS_Inst;
XGpio_Initialize(&GPIO_HYBRIDPIPELINETOPSW_VARS_Inst, GPIO_HYBRIDPIPELINETOPSW_VARS_DEVICE_ID);
currObj.GPIO_HYBRIDPIPELINETOPSW_VARS_Inst=GPIO_HYBRIDPIPELINETOPSW_VARS_Inst;


/// stringCurr initialise SOURCE : https://docs.google.com/spreadsheets/d/1qA65VvTDkKlL3Ou3-Us68UFqh0Ad6-piOz4uEJEVTds/edit#gid=0
currObj.stringCurr_DEFAULT[FPGA_RESET]=1;//RWL_EN_EXT
currObj.stringCurr_DEFAULT[RWL_EN_EXT]=0;//RWL_EN_EXT
currObj.stringCurr_DEFAULT[SC_DIN]=0;//SC_DIN
currObj.stringCurr_DEFAULT[ScanSel_3]=0;//ScanSel_3
currObj.stringCurr_DEFAULT[ScanSel_2]=0;//ScanSel_2
currObj.stringCurr_DEFAULT[ScanSel_1]=0;//ScanSel_1
currObj.stringCurr_DEFAULT[ScanSel_0]=0;//ScanSel_0
currObj.stringCurr_DEFAULT[CLK_A]=0;//CLK_A
currObj.stringCurr_DEFAULT[CLK_B]=0;//CLK_B
currObj.stringCurr_DEFAULT[CLK_C]=0;//CLK_C
currObj.stringCurr_DEFAULT[OEb_1]=0;//OEb_1
currObj.stringCurr_DEFAULT[RBL_PRE_EN_B]=0;//RBL_PRE_EN_B
currObj.stringCurr_DEFAULT[OEb_2]=0;//OEb_2
currObj.stringCurr_DEFAULT[WWL_EN]=0;//WWL_EN
currObj.stringCurr_DEFAULT[OEb_3]=0;//OEb_3
currObj.stringCurr_DEFAULT[IMG_Sel_Dec_2]=0;//IMG_Sel_Dec_2
currObj.stringCurr_DEFAULT[OEb_4]=0;//OEb_4
currObj.stringCurr_DEFAULT[IMG_Sel_Dec_1]=0;//IMG_Sel_Dec_1
currObj.stringCurr_DEFAULT[OEb_9]=0;//OEb_9
currObj.stringCurr_DEFAULT[IMG_Sel_Dec_0]=0;//IMG_Sel_Dec_0
currObj.stringCurr_DEFAULT[OEb_10]=0;//OEb_10
currObj.stringCurr_DEFAULT[RW_SA_EN]=0;//RW_SA_EN
currObj.stringCurr_DEFAULT[ADC0_S0]=0;//ADC0_S0
currObj.stringCurr_DEFAULT[SUBVoltPADConnect]=0;//SUBVoltPADConnect
currObj.stringCurr_DEFAULT[ADC0_S1]=0;//ADC0_S1
currObj.stringCurr_DEFAULT[MODE_R_WB]=1;//MODE_R_WB
currObj.stringCurr_DEFAULT[PRE_DR_EN]=0;//PRE_DR_EN
currObj.stringCurr_DEFAULT[unused0]=0;//unused0
currObj.stringCurr_DEFAULT[unused1]=0;//unused1
currObj.stringCurr_DEFAULT[CS_0]=0;//CS_0
currObj.stringCurr_DEFAULT[CS_1]=0;//CS_1
currObj.stringCurr_DEFAULT[ADC1_S0]=0;//ADC1_S0
currObj.stringCurr_DEFAULT[ADC1_S1]=0;//ADC1_S1
currObj.stringCurr_DEFAULT[BL_Sel_Dec_EXT_0]=0;//BL_Sel_Dec_EXT_0
currObj.stringCurr_DEFAULT[BL_Sel_Dec_EXT_1]=0;//BL_Sel_Dec_EXT_1
currObj.stringCurr_DEFAULT[unused2]=0;//unused2
currObj.stringCurr_DEFAULT[unused3]=0;//unused3
currObj.stringCurr_DEFAULT[unused4]=0;//unused4
currObj.stringCurr_DEFAULT[unused5]=0;//unused5
currObj.stringCurr_DEFAULT[RESET_GLOBALTIMER]=1;//RESET_GLOBALTIMER
currObj.stringCurr_DEFAULT[unused6]=0;//unused6
currObj.stringCurr_DEFAULT[CLK_DFF_EXT]=0;//CLK_DFF_EXT
currObj.stringCurr_DEFAULT[unused7]=0;//unused7
currObj.stringCurr_DEFAULT[DataCM_EN_EXT]=0;//DataCM_EN_EXT
currObj.stringCurr_DEFAULT[OEb_5]=0;//OEb_5
currObj.stringCurr_DEFAULT[DataSUB_EN_EXT]=0;//DataSUB_EN_EXT
currObj.stringCurr_DEFAULT[OEb_6]=0;//OEb_6
currObj.stringCurr_DEFAULT[Reset_SARLOGIC_EXT]=1;//Reset_SARLOGIC_EXT
currObj.stringCurr_DEFAULT[unused8]=0;//unused8
currObj.stringCurr_DEFAULT[DataResis_EN]=1;//DataResis_EN
currObj.stringCurr_DEFAULT[unused9]=0;//unused9
currObj.stringCurr_DEFAULT[RefResis_EN]=1;//RefResis_EN
currObj.stringCurr_DEFAULT[unused10]=0;//unused10
currObj.stringCurr_DEFAULT[CLK_SARLOGIC_IN_EXT]=0;//CLK_SARLOGIC_IN_EXT
currObj.stringCurr_DEFAULT[unused11]=0;//unused11
currObj.stringCurr_DEFAULT[unused12]=0;//unused12
currObj.stringCurr_DEFAULT[SA_EN_EXT]=0;//SA_EN_EXT
currObj.stringCurr_DEFAULT[AllVIN_n_EXT]=0;//AllVIN_n_EXT
currObj.stringCurr_DEFAULT[RefSUB_EN_EXT]=0;//RefSUB_EN_EXT
currObj.stringCurr_DEFAULT[unused13]=0;//unused13
currObj.stringCurr_DEFAULT[unused14]=0;//unused14
currObj.stringCurr_DEFAULT[unused15]=0;//unused15
currObj.stringCurr_DEFAULT[RefCM_EN_EXT]=0;//RefCM_EN_EXT
currObj.stringCurr_DEFAULT[unused16]=0;//unused16
currObj.stringCurr_DEFAULT[OEb_7]=0;//OEb_7
currObj.stringCurr_DEFAULT[ADCSTART_EXT]=0;//ADCSTART_EXT
currObj.stringCurr_DEFAULT[PRE_VCM_EXT]=0;//PRE_VCM_EXT
currObj.stringCurr_DEFAULT[OEb_8]=0;//OEb_8

//// setting TOPSW GPIO -> FOR INTERNAL TOPSW MODE
//u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
//u32 FPGA_RESET_REPEAT_UB=250;//13 bits, i.e. at most make it 2^12 - 1
//u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
//set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);

// setting TOPSW GPIO -> FOR HYBRID MODE
//u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
//u32 FPGA_RESET_REPEAT_UB=467;//13 bits, i.e. at most make it 2^12 - 1
//u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
//set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);

// Shifted to inside the function definition
////setting HYBRIDPIPELINETOPSW_VARS
//u8 RWL_EN_DELAY=3;
//u8 CM_EN_DELAY=2;
//u8 ADCSTART_DELAY=1;
//u8 SAMPLING_DELAY=3;
//u8 EVALUATE_DELAY=8;
//set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);


u8 ADC_bitMode=10;//default
u8 internal_hyb_B=1;//1=internal;0=hybrid
switch (ADC_bitMode)
{

	case 2:
	{

	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=26;//258ns required from simulation
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=4;
		u8 ADCSTART_DELAY=1;
		u8 SAMPLING_DELAY=3;
		u8 EVALUATE_DELAY=3;
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=135;//from TB_hybridBLpipeStateDiag simulation 1340ns from reset to done
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);

		break;
	}
	case 3:
	{
	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=31;//305ns required from sim
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=4;
		u8 ADCSTART_DELAY=1;
		u8 SAMPLING_DELAY=3;
		u8 EVALUATE_DELAY=4;
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=150;//from TB_hybridBLpipeStateDiag simulation 1470ns
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);

		break;
	}
	case 4:
	{
	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=36;//353ns required from sim
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=4;
		u8 ADCSTART_DELAY=1;
		u8 SAMPLING_DELAY=3;
		u8 EVALUATE_DELAY=5;
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=167;//from TB_hybridBLpipeStateDiag simulation 1640ns
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);
		break;
	}
	case 5:
	{
	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=40;//400ns required from sim
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=4;
		u8 ADCSTART_DELAY=1;
		u8 SAMPLING_DELAY=3;
		u8 EVALUATE_DELAY=6;
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=182;//from TB_hybridBLpipeStateDiag simulation 1790ns
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);
		break;
	}
	case 6:
	{
	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=45;//448ns required from simulation
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=4;
		u8 ADCSTART_DELAY=1;
		u8 SAMPLING_DELAY=3;
		u8 EVALUATE_DELAY=7;//72ns required round to 70ns
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=198;//from TB_hybridBLpipeStateDiag simulation 1950ns
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);
		break;
	}
	case 7:
	{

	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=50;//496ns required from simulation
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=4;
		u8 ADCSTART_DELAY=1;
		u8 SAMPLING_DELAY=3;
		u8 EVALUATE_DELAY=8;//84ns
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=214;//from TB_hybridBLpipeStateDiag simulation 2110ns
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);
		break;
	}
	case 8: //7-b ADC + 1X-SUB
	{

	//INTERNAL MODE RELATED TIMING GPIOS
			// 1. Repeat interval for one image
			XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
			XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
			u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=50;//496ns required from simulation
			XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

		//HYBRID MODE RELATED TIMING GPIOS
			// 2. Settings for hybrid mode TOPSW
			u8 RWL_EN_DELAY=1;
			u8 CM_EN_DELAY=4;
			u8 ADCSTART_DELAY=1;
			u8 SAMPLING_DELAY=3;
			u8 EVALUATE_DELAY=8;//84ns
			set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

		//COMMON to both HYBRID AND INTERNAL MODES
			// 3. Repeat interval for TOPSW periodic wave generation
			u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
			u32 FPGA_RESET_REPEAT_UB;
			if (internal_hyb_B)
			{
				FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
			}
			else
			{
				FPGA_RESET_REPEAT_UB=214;//from TB_hybridBLpipeStateDiag simulation 2110ns
			}
			u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
			set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);
			break;
	}
	case 9: //7-b ADC + 2X-SUB
	{

	//INTERNAL MODE RELATED TIMING GPIOS
			// 1. Repeat interval for one image
			XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
			XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
			u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=50;//496ns required from simulation
			XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

		//HYBRID MODE RELATED TIMING GPIOS
			// 2. Settings for hybrid mode TOPSW
			u8 RWL_EN_DELAY=1;
			u8 CM_EN_DELAY=4;
			u8 ADCSTART_DELAY=1;
			u8 SAMPLING_DELAY=3;
			u8 EVALUATE_DELAY=8;//84ns
			set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

		//COMMON to both HYBRID AND INTERNAL MODES
			// 3. Repeat interval for TOPSW periodic wave generation
			u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
			u32 FPGA_RESET_REPEAT_UB;
			if (internal_hyb_B)
			{
				FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
			}
			else
			{
				FPGA_RESET_REPEAT_UB=214;//from TB_hybridBLpipeStateDiag simulation 2110ns
			}
			u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
			set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);
			break;
	}
	case 10: //7-b ADC + 4X-SUB
	{
	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=50;//496ns required from simulation
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=4;
		u8 ADCSTART_DELAY=1;
		u8 SAMPLING_DELAY=3;
		u8 EVALUATE_DELAY=8;//84ns
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=214;//from TB_hybridBLpipeStateDiag simulation 2110ns
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);
		break;
	}

	default://Accuracy mode
	{
	//INTERNAL MODE RELATED TIMING GPIOS
		// 1. Repeat interval for one image
		XGpio GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst;
		XGpio_Initialize(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst, GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_ID);
		u16 GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA=170;//258ns required from simulation
		XGpio_DiscreteWrite(&GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_Inst,1,GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA);

	//HYBRID MODE RELATED TIMING GPIOS
		// 2. Settings for hybrid mode TOPSW
		u8 RWL_EN_DELAY=1;
		u8 CM_EN_DELAY=10;
		u8 ADCSTART_DELAY=10;
		u8 SAMPLING_DELAY=10;
		u8 EVALUATE_DELAY=100;
		set_HYBRIDPIPELINETOPSW_VARS_GPIO(currObj, RWL_EN_DELAY, CM_EN_DELAY, ADCSTART_DELAY, SAMPLING_DELAY,  EVALUATE_DELAY);

	//COMMON to both HYBRID AND INTERNAL MODES
		// 3. Repeat interval for TOPSW periodic wave generation
		u32 FPGA_RESET_REPEAT_LB=1;//13 bits, i.e. at most make it 2^12 - 1
		u32 FPGA_RESET_REPEAT_UB;
		if (internal_hyb_B)
		{
			FPGA_RESET_REPEAT_UB=(GPIO_INTERNAL_TIMING_1_IMG_TIME_GPIO_DATA+1)*4+1;//13 bits, i.e. at most make it 2^12 - 1
		}
		else
		{
			FPGA_RESET_REPEAT_UB=130;//from TB_hybridBLpipeStateDiag simulation
		}
		u32 FPGA_RESET_REPEAT_NUMREPEAT=4;//for infinity set the value as 4
		set_TOPSW_GPIO_bank1(currObj, FPGA_RESET_REPEAT_LB, FPGA_RESET_REPEAT_UB, FPGA_RESET_REPEAT_NUMREPEAT);


		break;
	}

}




return currObj;
}
