%generateAlphas
%IMC_RBL_ReadStacks
load('D:\Xilinx\Vivado_2018_Projs\IMC_CHIP_2023\PCB_v3\MATLAB_CONTROL\Control_Codes\Testing\017_ReadStackAlphaMeasurement\IMC_RBL_ReadStacks.mat');
%RefIMC_RBL_ReadStacks
load('D:\Xilinx\Vivado_2018_Projs\IMC_CHIP_2023\PCB_v3\MATLAB_CONTROL\Control_Codes\Testing\017_ReadStackAlphaMeasurement\RefIMC_RBL_ReadStacks.mat');
alpha_DLs=(IMC_RBL_ReadStacks)/mean(IMC_RBL_ReadStacks,'all');
alpha_RLs=(RefIMC_RBL_ReadStacks)/mean(RefIMC_RBL_ReadStacks,'all');
alpha_DLStore=reshape(alpha_DLs,72,1024);
alphaOld_DLStore=alpha_DLStore';
alpha_RLStore=reshape(alpha_RLs,16,1024);
alphaOld_RLStore=alpha_RLStore';
IMC_RBL_ReadStacks=(reshape(IMC_RBL_ReadStacks,72,1024))';
ImeanOld_DLStore=mean(IMC_RBL_ReadStacks(1:10,:),'all');
save('./alphaStored/OLDalphas.mat','alphaOld_DLStore','alphaOld_RLStore','ImeanOld_DLStore');

%IMC_RBL_ReadStacks
load('D:\Xilinx\Vivado_2018_Projs\IMC_CHIP_2023\PCB_v3\MATLAB_CONTROL\Control_Codes\Testing\017_ReadStackAlphaMeasurement\AlphaMeasure_RWL474mV\IMC_RBL_ReadStacks.mat');
alpha_DLs=(IMC_RBL_ReadStacks)/mean(IMC_RBL_ReadStacks,'all');
alpha_DLStore=reshape(alpha_DLs,72,10);
alphaNew_DLStore=alpha_DLStore';
ImeanNew_DLStore=mean(IMC_RBL_ReadStacks,'all');
save('./alphaStored/NEWalphas.mat','alphaNew_DLStore','ImeanNew_DLStore');