function [adc_VPVN,adc_AUX00] = analyseRealTime_ADC(filePath)
%ANALYSEREALTIME_ADC analyse ADC results ina loop in realtime
%   Detailed explanation goes here

b = find( filePath == '\', 1, 'last' ) ; 
sourceFileName = filePath( ( b + 1 )  : ( end - 4 ) ) ;
driverCode_fileName         = sprintf( '/%s', sourceFileName ) ;
filePath            = '.' ;
fpgaReceivedFile_name       = [ filePath '/fpgaRcvdFiles' driverCode_fileName ] ;
[    ~ ...
            , adc_VPVN ...
            , adc_AUX00 ...
            ,    ~    ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~  ...
            ,    ~ ...
           ,     ~ ] = decrypt_and_RSC( fpgaReceivedFile_name ) ;
 
end

