% Generate names.mat
% Got the mapping from C code custom_h.h
clear;
description = sprintf( 'generated by %s on %s', mfilename, date ) ;

%%%%%%%%%%%%%%%%%%%%%%%

SA_SC=0;
ADC_SC=1;
AdderTree_SC=2;
SARTIMING_OUT_SC=3;
WRITE_2_SC=4;
WRITE_1_SC=5;
WRITE_0_SC=6;
IMC_RBL_SC=7;
IMC_VOut_SC=8;
WWL_SC=9;
FLOATADC_SC=10;
SARTIMING_IN_SC=11;
ControlPath_SC=12;
Reset_DFF=13;
SC_DEFAULT=SA_SC;
%%%%%%%%%%%%%%%%%%%%%
save('./SC_NUMS.mat');
