% Generate names.mat
% Got the mapping from https://docs.google.com/spreadsheets/d/1-dnSEVlwWhkfoKg_O_cuGsctOFnojoC4A829bs_4FjE/edit#gid=1066741019
clear;
description = sprintf( 'generated by %s on %s', mfilename, date ) ;

names_GPIO = ["ADCSTART_EXT","AllVIN_n_EXT","BL_Sel_Dec_EXT_1","BL_Sel_Dec_EXT_0","CLK_A","CLK_B","CLK_C","CLK_DFF_EXT","CLK_SARLOGIC_IN_EXT","CS_1","CS_0","DataCM_EN_EXT","DataResis_EN","DataSUB_EN_EXT","IMG_Sel_Dec_2","IMG_Sel_Dec_1","IMG_Sel_Dec_0","MODE_R_WB","PRE_DR_EN","PRE_VCM_EXT","RBL_PRE_EN_B","RESET_GLOBALTIMER","RWL_EN_EXT","RefCM_EN_EXT","RefResis_EN","RefSUB_EN_EXT","Reset_SARLOGIC_EXT","RW_SA_EN","SA_EN_EXT","SC_DIN","SUBVoltPADConnect","ScanSel_3","ScanSel_2","ScanSel_1","ScanSel_0","WWL_EN","OEb_1","OEb_2","OEb_3","OEb_4","OEb_5","OEb_6","OEb_7","OEb_8","OEb_9","OEb_10","ADC0_S1","ADC0_S0","ADC1_S1","ADC1_S0","unused0","unused1","unused2","unused3","unused4","unused5","unused6","unused7","unused8","unused9","unused10","unused11","unused12","unused13","unused14","unused15","unused16","FPGA_RESET"];

ADCSTART_EXT=0;
AllVIN_n_EXT=1;
BL_Sel_Dec_EXT_1=2;
BL_Sel_Dec_EXT_0=3;
CLK_A=4;
CLK_B=5;
CLK_C=6;
CLK_DFF_EXT=7;
CLK_SARLOGIC_IN_EXT=8;
CS_1=9;
CS_0=10;
DataCM_EN_EXT=11;
DataResis_EN=12;
DataSUB_EN_EXT=13;
IMG_Sel_Dec_2=14;
IMG_Sel_Dec_1=15;
IMG_Sel_Dec_0=16;
MODE_R_WB=17;
PRE_DR_EN=18;
PRE_VCM_EXT=19;
RBL_PRE_EN_B=20;
RESET_GLOBALTIMER=21;
RWL_EN_EXT=22;
RefCM_EN_EXT=23;
RefResis_EN=24;
RefSUB_EN_EXT=25;
Reset_SARLOGIC_EXT=26;
RW_SA_EN=27;
SA_EN_EXT=28;
SC_DIN=29;
SUBVoltPADConnect=30;
ScanSel_3=31;
ScanSel_2=32;
ScanSel_1=33;
ScanSel_0=34;
WWL_EN=35;
OEb_1=36;
OEb_2=37;
OEb_3=38;
OEb_4=39;
OEb_5=40;
OEb_6=41;
OEb_7=42;
OEb_8=43;
OEb_9=44;
OEb_10=45;
ADC0_S1=46;
ADC0_S0=47;
ADC1_S1=48;
ADC1_S0=49;
unused0=50;
unused1=51;
unused2=52;
unused3=53;
unused4=54;
unused5=55;
unused6=56;
unused7=57;
unused8=58;
unused9=59;
unused10=60;
unused11=61;
unused12=62;
unused13=63;
unused14=64;
unused15=65;
unused16=66;
FPGA_RESET=67;

varsIn.ADCSTART_EXT=ADCSTART_EXT;
varsIn.AllVIN_n_EXT=AllVIN_n_EXT;
varsIn.BL_Sel_Dec_EXT_1=BL_Sel_Dec_EXT_1;
varsIn.BL_Sel_Dec_EXT_0=BL_Sel_Dec_EXT_0;
varsIn.CLK_A=CLK_A;
varsIn.CLK_B=CLK_B;
varsIn.CLK_C=CLK_C;
varsIn.CLK_DFF_EXT=CLK_DFF_EXT;
varsIn.CLK_SARLOGIC_IN_EXT=CLK_SARLOGIC_IN_EXT;
varsIn.CS_1=CS_1;
varsIn.CS_0=CS_0;
varsIn.DataCM_EN_EXT=DataCM_EN_EXT;
varsIn.DataResis_EN=DataResis_EN;
varsIn.DataSUB_EN_EXT=DataSUB_EN_EXT;
varsIn.IMG_Sel_Dec_2=IMG_Sel_Dec_2;
varsIn.IMG_Sel_Dec_1=IMG_Sel_Dec_1;
varsIn.IMG_Sel_Dec_0=IMG_Sel_Dec_0;
varsIn.MODE_R_WB=MODE_R_WB;
varsIn.PRE_DR_EN=PRE_DR_EN;
varsIn.PRE_VCM_EXT=PRE_VCM_EXT;
varsIn.RBL_PRE_EN_B=RBL_PRE_EN_B;
varsIn.RESET_GLOBALTIMER=RESET_GLOBALTIMER;
varsIn.RWL_EN_EXT=RWL_EN_EXT;
varsIn.RefCM_EN_EXT=RefCM_EN_EXT;
varsIn.RefResis_EN=RefResis_EN;
varsIn.RefSUB_EN_EXT=RefSUB_EN_EXT;
varsIn.Reset_SARLOGIC_EXT=Reset_SARLOGIC_EXT;
varsIn.RW_SA_EN=RW_SA_EN;
varsIn.SA_EN_EXT=SA_EN_EXT;
varsIn.SC_DIN=SC_DIN;
varsIn.SUBVoltPADConnect=SUBVoltPADConnect;
varsIn.ScanSel_3=ScanSel_3;
varsIn.ScanSel_2=ScanSel_2;
varsIn.ScanSel_1=ScanSel_1;
varsIn.ScanSel_0=ScanSel_0;
varsIn.WWL_EN=WWL_EN;
varsIn.OEb_1=OEb_1;
varsIn.OEb_2=OEb_2;
varsIn.OEb_3=OEb_3;
varsIn.OEb_4=OEb_4;
varsIn.OEb_5=OEb_5;
varsIn.OEb_6=OEb_6;
varsIn.OEb_7=OEb_7;
varsIn.OEb_8=OEb_8;
varsIn.OEb_9=OEb_9;
varsIn.OEb_10=OEb_10;
varsIn.ADC0_S1=ADC0_S1;
varsIn.ADC0_S0=ADC0_S0;
varsIn.ADC1_S1=ADC1_S1;
varsIn.ADC1_S0=ADC1_S0;
varsIn.unused0=unused0;
varsIn.unused1=unused1;
varsIn.unused2=unused2;
varsIn.unused3=unused3;
varsIn.unused4=unused4;
varsIn.unused5=unused5;
varsIn.unused6=unused6;
varsIn.unused7=unused7;
varsIn.unused8=unused8;
varsIn.unused9=unused9;
varsIn.unused10=unused10;
varsIn.unused11=unused11;
varsIn.unused12=unused12;
varsIn.unused13=unused13;
varsIn.unused14=unused14;
varsIn.unused15=unused15;
varsIn.unused16=unused16;
varsIn.FPGA_RESET=FPGA_RESET;

%%%%%%%%%%%%%%%%%%%%%%%

scanChainNames = {
    
          'SA_SC';
      
          'ADC_SC';
      
          'AdderTree_SC';
      
          'SARTIMING_OUT_SC';
      
          'WRITE_2_SC';
      
          'WRITE_1_SC';
      
          'WRITE_0_SC';
      
          'IMC_RBL_SC';
      
          'IMC_VOut_SC';
      
          'WWL_SC';
      
          'FLOATADC_SC';
      
          'SARTIMING_IN_SC';
      
          'ControlPath_SC';
      
          'Reset_DFF';
};

%%%%%%%%%%%%%%%%%%%%%
save('./names.mat');