function GLOBALTIMER_scanInPattern = GLOBALTIMER_scanInPattern_generate( GLOBALTIMER )
GLOBALTIMER.PB_PM='0';
GLOBALTIMER_scanInPattern = [
            GLOBALTIMER.ADCBITMODE, ...
            GLOBALTIMER.ADCSTART_TIME, ...
            GLOBALTIMER.AllVIN_n_LB, ...
            GLOBALTIMER.AllVIN_n_UB, ...
            GLOBALTIMER.BPSDELAY, ...
            GLOBALTIMER.CLK_DFF_LB, ...
            GLOBALTIMER.CLK_DFF_UB, ...
            GLOBALTIMER.CLK_SARLOGIC_IN_LB, ...
            GLOBALTIMER.CLK_SARLOGIC_IN_UB, ...
            GLOBALTIMER.DATA_CM_EN_TIME, ...
            GLOBALTIMER.DATA_SUB_EN_TIME, ...
            GLOBALTIMER.EXT_LOCB, ...
            GLOBALTIMER.NUMBLS_TARGET, ...
            GLOBALTIMER.OFF_IMCB, ...
            GLOBALTIMER.PRE_VCM_LB, ...
            GLOBALTIMER.PRE_VCM_UB, ...
            GLOBALTIMER.REF_CM_EN_TIME, ...
            GLOBALTIMER.REF_SUB_EN_TIME, ...
            GLOBALTIMER.Reset_SARLOGIC_LB, ...
            GLOBALTIMER.Reset_SARLOGIC_UB, ...
            GLOBALTIMER.SA_EN_LB, ...
            GLOBALTIMER.SA_EN_UB, ...
            GLOBALTIMER.count_STOP, ...
            GLOBALTIMER.PB_PM ...  
];
GLOBALTIMER_scanInPattern = string_toBitString( GLOBALTIMER_scanInPattern ) ;
end
function bitStringOut=string_toBitString( stringIn )
    bitStringOut = stringIn - '0' ;
end