function [fitresult, gof] = createFit(ADC_act, ADC_exp)
%CREATEFIT(ADC_ACT,ADC_EXP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: ADC_act
%      Y Output: ADC_exp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Aug-2023 15:38:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ADC_act, ADC_exp );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'ADC_exp vs. ADC_act', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'ADC_act', 'Interpreter', 'none' );
ylabel( 'ADC_exp', 'Interpreter', 'none' );
grid on
end


